version: '3.3'
services:
  reactapp: 
    container_name: reactapp
    restart: always
    build: ./client/
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - nodeapp
    volumes:
      - ./data/reactapp/build:/home/react/app/build
  nodeapp:
    container_name: nodeapp
    restart: always
    build: ./server/
    ports:
      - '5000:5000'
    external_links:
      - mongo
    volumes:
      - ./data/nodejsapp/files/images:/home/node/app/files/images
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo-db/mongo:/data/db
      - ./data/mongo/mongo-config:/data/configdb
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nodejsapp/files/images:/var/www/nodejsapp/files/images
      - ./data/reactapp/build:/var/www/reactapp/build
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - reactapp
    external_links:
      - reactapp
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email wmfarooqi05@gmail.com --agree-tos --no-eff-email --staging -d alhafeez.qa  -d www.alhafeez.qa
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
