version: '3.8'
services:
  reactapp: 
    container_name: reactapp
    restart: always
    build: ./client/
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: ./server/
    ports:
      - '5000:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  nginx-app:
    container_name: nginx-app
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - reactapp
    external_links:
      - reactapp
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email wmfarooqi05@gmail.com --agree-tos --no-eff-email --staging -d alhafeez.qa  -d www.alhafeez.qa

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx-app
    command: certonly --webroot --webroot-path=/var/www/html --email wmfarooqi05@gmail.com --agree-tos --no-eff-email --staging -d alhafeez.qa  -d www.alhafeez.qa
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"