export default {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_INPROGRESS: "USERS_LOGIN_INPROGRESS",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_INITIVE: "UPDATE_USER_INITIVE",
  LOGOUT: "USERS_LOGOUT",
  UPDATE_FAILURE:'FAILED_TO_UPDATE',
};
