export default {
  GETALL_PRODUCTS_REQUEST: 'PRODUCTS_GETALL_REQUEST',
  GETALL_PRODUCTS_INPROGRESS: 'PRODUCTS_GETALL_INPROGRESS',
  GETALL_PRODUCTS_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
  GETALL_PRODUCTS_FAILURE: 'PRODUCTS_GETALL_FAILURE',

  GET_PRODUCT_REQUEST: 'PRODUCT_GET_REQUEST',
  GET_PRODUCT_INPROGRESS: 'PRODUCT_GET_INPROGRESS',
  GET_PRODUCT_SUCCESS: 'PRODUCT_GET_SUCCESS',
  GET_PRODUCT_FAILURE: 'PRODUCT_GET_FAILURE',

  ADD_PRODUCTS_TO_REDUCER_INITIATE: 'ADD_PRODUCTS_TO_REDUCER_INITIATE',
  ADD_PRODUCTS_TO_REDUCER: 'ADD_PRODUCTS_TO_REDUCER',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  UPDATE_PRODUCTS_ATER_LOGIN:'UPDATE_PRODUCTS_ATER_LOGIN'
};
