export default {
  OPEN_PRODUCT_DIALOG: 'OPEN_PRODUCT_DIALOG',
  OPEN_PRODUCT_DIALOG_INITIATE: 'OPEN_PRODUCT_DIALOG_INITIATE',
  CLOSE_PRODUCT_DIALOG: 'CLOSE_PRODUCT_DIALOG',
  CLOSE_PRODUCT_DIALOG_INITIATE: 'CLOSE_PRODUCT_DIALOG_INITIATE',

  ADD_PRODUCTS_IN_PRODUCT_DIALOG_INITIATE: 'ADD_PRODUCTS_IN_PRODUCT_DIALOG_INITIATE',
  ADD_PRODUCTS_IN_PRODUCT_DIALOG_INPROGRESS: 'ADD_PRODUCTS_IN_PRODUCT_DIALOG_INPROGRESS',
  ADD_PRODUCTS_IN_PRODUCT_DIALOG_SUCCESS: 'ADD_PRODUCTS_IN_PRODUCT_DIALOG_SUCCESS',
  ADD_PRODUCTS_IN_PRODUCT_DIALOG_ERROR: 'ADD_PRODUCTS_IN_PRODUCT_DIALOG_ERROR',
  SET_CART_FLAG: 'SET_CART_FLAG',
  SET_WISHLIST_FLAG: 'SET_WISHLIST_FLAG'
};
