export default {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_INPROGRESS: 'USERS_REGISTER_INPROGRESS',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
}