export default searchConstants = {
  GET_SEARCH_REQUEST: 'SEARCH_GET_REQUEST',
  GET_SEARCH_INPROGRESS: 'SEARCH_GET_INPROGRESS',
  GET_SEARCH_SUCCESS: 'SEARCH_GET_SUCCESS',
  GET_SEARCH_FAILURE: 'SEARCH_GET_FAILURE',
};