export default shopConstants = {
  GETALL_SHOPS_REQUEST: 'SHOPS_GETALL_REQUEST',
  GETALL_SHOPS_INPROGRESS: 'SHOPS_GETALL_INPROGRESS',
  GETALL_SHOPS_SUCCESS: 'SHOPS_GETALL_SUCCESS',
  GETALL_SHOPS_FAILURE: 'SHOPS_GETALL_FAILURE',

  GET_SHOP_REQUEST: 'SHOP_GET_REQUEST',
  GET_SHOP_INPROGRESS: 'SHOP_GET_INPROGRESS',
  GET_SHOP_SUCCESS: 'SHOP_GET_SUCCESS',
  GET_SHOP_FAILURE: 'SHOP_GET_FAILURE',
};