export default {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_INPROGRESS: 'USERS_REGISTER_INPROGRESS',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  GETALL_USERS_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_USERS_INPROGRESS: 'USERS_GETALL_INPROGRESS',
  GETALL_USERS_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_USERS_FAILURE: 'USERS_GETALL_FAILURE',

  GET_USER_REQUEST: 'USER_GET_REQUEST',
  GET_USER_INPROGRESS: 'USER_GET_INPROGRESS',
  GET_USER_SUCCESS: 'USER_GET_SUCCESS',
  GET_USER_FAILURE: 'USER_GET_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_INPROGRESS: 'USERS_DELETE_INPROGRESS',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};