export const ADD_WISH_LIST_ITEM = "ADD_ITEM_IN_WISH_LIST";
export const DELETE_WISH_LIST_ITEM = "DELETE_ITEM_FROM_WISH_LIST";
export const ADD_WISH_LIST_ITEM_INITIATE = "ADD_ITEM_IN_WISH_LIST_INITIATE";
export const DELETE_WISH_LIST_ITEM_INITIATE ="DELETE_ITEM_FROM_WISH_LIST_INITIATE";
export const SAVE_WISH_LIST_ITEMS = "SAVE_WISH_LIST_ITEMS";
export const EMPTY_WISH_LIST_DISPATCH = "EMPTY_WISH_LIST_DISPATCH"
